### PR TITLE
Update WikibaseRepo::getEntityNamespaceLookup() call

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Bug: [T277313](https://phabricator.wikimedia.org/T277313)
Depends-On: [Ief409a501aac74e7b6df4e440113cd552dba3c74](https://gerrit.wikimedia.org/r/c/672469)

### CODE REVIEW

**Comment by Ladsgroup** [comment]
Let me once that's merged and I'll merge this one.  (Sidenote: We should clean up travis here).

**Review by itamargiv — APPROVED** [review]
LGTM, I'll adhere to what @Ladsgroup said before though, The base change in WB is merged now.

**Comment by lucaswerkmeister** [comment]
Yeah, tbh I’m not sure what we do with this extension in general (does it still work? I haven’t used it in a long time). But I guess we can at least merge this change, as long as there’s no expectation that WikibaseImport works with older MediaWiki/Wikibase versions.

**Comment by Ladsgroup** [comment]
Let's merge it for now as it's trivial enough. Let's make a ticket for determining future of it.

**Comment by aot29** [comment]
There is this popular [Wikibase Docker bundle](https://github.com/wmde/wikibase-docker) by wmde which uses Mediawiki 1.35. WikibaseImport will work with this bundle when checking out [c1233da](https://github.com/Wikidata/WikibaseImport/tree/c1233da6b7122c55c95d9d925b8f4162de8807e7).

**Pull request merged**
